import { test } from 'node:test';
import assert from 'node:assert/strict';
import { GraphClient, loadGraph } from './graph.js';
import express from 'express';
import { installAdmin } from './admin.js';
import { UserDatabase } from './database.js';
const tenant = 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee';
const object = '12345678-1234-1234-1234-123456789abc';
const target = '22222222-3333-4444-5555-666666666666';
test('Graph token caching, fixed assignment target, invitation payload and safe errors', async () => {
  const calls: { url: string; body?: string }[] = [];
  const transport = (async (url: any, init: any) => {
    calls.push({ url: String(url), body: init.body?.toString() });
    const data = String(url).includes('/token') ? { access_token: 'private-token', expires_in: 3600 } : String(url).includes('?$select=id') ? { displayName: 'SAML', appRoles: [] } : String(url).endsWith('/invitations') ? { invitedUser: { id: object } } : String(url).includes('$top') ? { value: [] } : { id: 'assignment' };
    return new Response(JSON.stringify(data), { status: 200 });
  }) as typeof fetch;
  const graph = new GraphClient(tenant, target, 'private-secret', target, 'https://myapps.microsoft.com/', transport);
  const role = await graph.check();
  assert.equal(await graph.invite('partner@example.com', 'Partner'), object);
  await graph.assign(object, role.roleId);
  assert.equal(calls.filter(c => c.url.includes('/token')).length, 1);
  assert.ok(!calls.some(c => c.url.includes('$filter')));
  const invite = JSON.parse(calls.find(c => c.url.endsWith('/invitations'))!.body!);
  assert.equal(invite.sendInvitationMessage, true);
  assert.equal(invite.invitedUserType, 'Guest');
  assert.equal(JSON.parse(calls.at(-1)!.body!).resourceId, target);
  const bad = new GraphClient(tenant, target, 'private-secret', target, 'https://myapps.microsoft.com/', (async () => new Response('private-secret', { status: 401 })) as typeof fetch);
  await assert.rejects(() => bad.check(), e => e instanceof Error && !e.message.includes('private-secret'));
  assert.throws(() => loadGraph({ GRAPH_TENANT_ID: tenant }));
});
test('invitation authorization, duplicate prevention and assignment retry without email resend', async t => {
  const db = new UserDatabase(':memory:'); t.after(() => db.close());
  const identity = { tenantId: tenant, objectId: object, nameId: 'admin', name: 'Admin', email: null };
  const user = db.register(identity); db.db.prepare('INSERT INTO common_admins VALUES(?)').run(user.id);
  let sends = 0, fail = true;
  const graph = { tenant, check: async () => ({ name: 'SAML', roleId: target }), invite: async () => { sends++; return target; }, assign: async () => { if (fail) throw new Error('Assignment failed'); } } as unknown as GraphClient;
  const app = express();
  app.use((req, _res, next) => { req.session = { user: identity, csrf: 'csrf' } as any; next(); });
  installAdmin(app, db, 'http://localhost:5173', graph);
  const server = app.listen(0, '127.0.0.1'); await new Promise<void>(r => server.once('listening', r));
  t.after(() => new Promise<void>(r => server.close(() => r())));
  const address = server.address() as { port: number };
  const headers = { Origin: 'http://localhost:5173', 'X-CSRF-Token': 'csrf', 'Content-Type': 'application/json' };
  const call = (path: string, body: unknown, h = headers) => fetch(`http://127.0.0.1:${address.port}/api/admin/${path}`, { method: 'POST', headers: h, body: JSON.stringify(body) });
  const body = { email: 'partner@example.com', name: 'Partner', company: 'Partner Co' };
  assert.equal((await call('invitations', body, { ...headers, Origin: 'https://evil.example' })).status, 403);
  assert.equal((await call('invitations', body)).status, 502);
  const row = db.db.prepare('SELECT id,status FROM invitations').get() as { id: string; status: string };
  assert.equal(row.status, 'assignment_failed');
  assert.equal((await call('invitations', body)).status, 409);
  fail = false;
  assert.equal((await call(`invitations/${row.id}/assign`, {})).status, 200);
  assert.equal(sends, 1);
  assert.equal(db.db.prepare('SELECT * FROM external_identities').all().length, 1);
  db.db.prepare('DELETE FROM common_admins').run(); db.grant(user.id, 'mobile', 'admin');
  assert.equal((await call('invitations', body)).status, 403);
});
